version: "3"
services:

  backend:
    container_name: backend
    build: ./server
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    # volumes:
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env

  frontend:
    container_name: frontend
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    env_file:
      - .env
    
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./user_conf.d:/etc/nginx/user_conf.d
    
