version: "3"
services:

  backend:
    container_name: backend
    build: ./server
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    # volumes:
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env

  frontend:
    container_name: frontend
    restart: always
    build: ./client
    ports: 
      - "2000:2000"
    env_file:
      - .env
    
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports: 
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_storage:



  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./user_conf.d:/etc/nginx/user_conf.d
    
