"""empty message

Revision ID: 37383ef282bc
Revises: 
Create Date: 2021-08-05 09:32:54.978943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37383ef282bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('playlist_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
